### ISSUE TITLE
Import failure: based on typeError or invalid URL?

### ISSUE THREAD

**Issue by jason-mehmel** [huseyz/obsidian-wallabag#45]
I got the authentication to work okay, but can't get the actual sync happening. When I went to the Obsidian console (ctrl-shift-i) I found these in the log:

I'm not sure if the URL is based on the wallabag instance I'm using (which is just the app.wallabag.it URL) or something internal to Obsidian.

```
plugin:wallabag:587

TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at new ClientRequest (node:electron/js2c/browser_init:2:111512)
    at Object.request (node:electron/js2c/browser_init:2:48235)
    at IpcMainImpl.<anonymous> (/home/jason/.config/obsidian/obsidian-1.7.7.asar/main.js:38:7204)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82388)
    at WebContents.emit (node:events:519:28
```

```
plugin:wallabag:587

Error: Request failed, status 400
    at new t (app.js:1:1925609)
    at PU (app.js:1:1925801)
    at app.js:1:1926480
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
```

**Comment by huseyz** [comment]
Make sure you use the full URL. i.e., with schema. probably "https://app.wallabag.it"

**Comment by jason-mehmel** [comment]
I am using the full URL! That one exactly. I also tried just app.wallabag.it

When I hit 'sync wallabag articles' I can't tell if anything is going on, which is why I checked the console.

Is there a way to control the order of what is synced? I have a LOT of articles saved so maybe it's crashing due to the scale. But I can make do with only the most recent archived articles, like from the last month or so.

**Comment by jason-mehmel** [comment]
Some more developments:

I have been able to get a few articles synched... ones that I have archived. Only 3 so far, though, and I'm not sure why only 3!

**Comment by jason-mehmel** [comment]
Okay, more are syncing.

Here's something I'm wondering that might not be documented:

Does it only start syncing articles after being authenticated with Wallabag? As in, it's only syncing the articles from that point forwards? That would line up with the behaviour I've seen so far, but it's not what I expected!

I had expected to sync all articles in my wallabag account, not just the newest ones, although I can work with this development!

**Comment by cschritt** [comment]
I noticed the same behavior. Only articles that I added since I authenticated the obsidian plugin are synced.

Might be related to #22
